# ============================================================
# backend/app/app/documents/services/document_service.py
# ============================================================
#
# Purpose:
#   Business logic for the documents domain. Handles the R2
#   presigned upload flow and the document CRUD operations.
#
# Design:
#   The presigned URL is generated by boto3's generate_presigned_url
#   against the R2 endpoint. The URL is valid for 15 minutes,
#   long enough for a browser upload of even a large PDF.
#
#   Deletion removes the database row and the R2 object. If the
#   R2 delete fails, the row is still removed (the R2 object
#   becomes orphaned but is not a security risk since it is
#   private). A future maintenance job can sweep orphaned objects.
#
# Consumed by:
#   - backend/app/app/api/v1/documents.py
# ============================================================

import uuid
from datetime import datetime, timezone

from fastapi import HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.settings import get_settings
from app.documents.models.document import Document
from app.documents.repositories.document_repository import DocumentRepository
from app.documents.schemas.document_schemas import (
    DocumentCreateIn,
    DocumentOut,
    SignedUploadOut,
    SignUploadIn,
)
from app.integrations.r2 import get_r2_client

# ==================================================
# DOCUMENT SERVICE
# ==================================================

_SIGNED_URL_EXPIRY = 15 * 60  # 15 minutes in seconds


class DocumentService:
    def __init__(self, db: AsyncSession) -> None:
        self._db = db
        self._repo = DocumentRepository(db)

    # ==================================================
    # SIGNED UPLOAD
    # ==================================================

    def sign_upload(
        self, account_id: uuid.UUID, data: SignUploadIn
    ) -> SignedUploadOut:
        settings = get_settings()
        r2 = get_r2_client()
        # Key pattern: {account_id}/vehicles/{vehicle_id}/docs/{timestamp}/{filename}
        ts = int(datetime.now(timezone.utc).timestamp())
        safe_name = data.filename.replace(" ", "_")
        r2_key = (
            f"{account_id}/vehicles/{data.vehicle_id}/docs/{ts}/{safe_name}"
        )
        upload_url = r2.generate_presigned_url(
            "put_object",
            Params={
                "Bucket": settings.r2_bucket_name,
                "Key": r2_key,
                "ContentType": data.content_type,
            },
            ExpiresIn=_SIGNED_URL_EXPIRY,
        )
        return SignedUploadOut(
            upload_url=upload_url,
            r2_key=r2_key,
            expires_in=_SIGNED_URL_EXPIRY,
        )

    # ==================================================
    # DOCUMENT CRUD
    # ==================================================

    # ------------------------------ Create ----------------------------------

    async def create_document(
        self,
        account_id: uuid.UUID,
        created_by: uuid.UUID,
        data: DocumentCreateIn,
    ) -> DocumentOut:
        doc = await self._repo.create(account_id, created_by, data)
        return DocumentOut.model_validate(doc)

    # ------------------------------ List ------------------------------------

    async def list_documents(
        self, vehicle_id: uuid.UUID, account_id: uuid.UUID
    ) -> list[DocumentOut]:
        docs = await self._repo.list_by_vehicle(vehicle_id, account_id)
        return [DocumentOut.model_validate(d) for d in docs]

    # ------------------------------ Delete ----------------------------------

    async def delete_document(
        self, document_id: uuid.UUID, account_id: uuid.UUID
    ) -> None:
        doc = await self._repo.get_by_id(document_id, account_id)
        if doc is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND, detail="Document not found."
            )
        # ~~~~~~~~~ Remove R2 object first, then the row ~~~~~~~~~
        # If R2 deletion fails, the row is still removed. The object becomes
        # orphaned but remains private and a future sweep can clean it.
        settings = get_settings()
        try:
            r2 = get_r2_client()
            r2.delete_object(Bucket=settings.r2_bucket_name, Key=doc.r2_key)
        except Exception:
            pass  # do not block row deletion on R2 errors
        await self._repo.delete(doc)
